version: '3.8'

services:
  api:
    image: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5017:80"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=db;Database=BooksDB;User=sa;Password=SecurePassword&321;TrustServerCertificate=True;
      - PATH_BASE=/swagger
  
  db:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      SA_PASSWORD: "SecurePassword&321"
      ACCEPT_EULA: "Y"